### ISSUE TITLE
[OCP\Files\StorageInvalidException] Sabre\HTTP\ClientHttpException: Unauthorized

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/files_fulltextsearch#11]
`fulltextsearch:index`aborted with the following Exceptions:

```
 USER: user234503

                                                
  [OCP\Files\StorageInvalidException]           
  Sabre\HTTP\ClientHttpException: Unauthorized  
```

These were the corresponding entries wihin nextcloud.log:
```
{"reqId":"ymDiNxFvBrNANiLmHQCe","level":3,"time":"2018-04-17T20:32:17+02:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientHttpException\",\"Message\":\"Unauthorized\",\"Code\":401,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(231): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(263): Sabre\\\\DAV\\\\Client->propFind('https:\\\/\\\/togethe...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(320): OC\\\\Files\\\\Storage\\\\DAV->propfind('.noindex')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(240): OC\\\\Files\\\\Storage\\\\DAV->file_exists('.noindex')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OCA\\\\Files_Sharing\\\\External\\\\Storage->file_exists('.noindex')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(244): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('.noindex')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('.noindex')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1322): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('.noindex')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1371): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), '.noindex', '\\\/user234503\\\/file...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(198): OC\\\\Files\\\\View->getFileInfo('\\\/user234503\\\/file...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(133): OC\\\\Files\\\\Node\\\\Root->get('\\\/user234503\\\/file...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(142): OC\\\\Files\\\\Node\\\\Folder->get('.noindex')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Service\\\/FilesService.php(154): OC\\\\Files\\\\Node\\\\Folder->nodeExists('.noindex')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Service\\\/FilesService.php(175): OCA\\\\Files_FullTextSearch\\\\Service\\\\FilesService->getFilesFromDirectory(Object(OCA\\\\FullTextSearch\\\\Model\\\\Runner), 'user234503', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Service\\\/FilesService.php(133): OCA\\\\Files_FullTextSearch\\\\Service\\\\FilesService->getFilesFromDirectory(Object(OCA\\\\FullTextSearch\\\\Model\\\\Runner), 'user234503', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Provider\\\/FilesProvider.php(186): OCA\\\\Files_FullTextSearch\\\\Service\\\\FilesService->getFilesFromUser(Object(OCA\\\\FullTextSearch\\\\Model\\\\Runner), 'user234503')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/fulltextsearch\\\/lib\\\/Service\\\/IndexService.php(122): OCA\\\\Files_FullTextSearch\\\\Provider\\\\FilesProvider->generateIndexableDocuments('user234503')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/fulltextsearch\\\/lib\\\/Command\\\/Index.php(146): OCA\\\\FullTextSearch\\\\Service\\\\IndexService->indexProviderContentFromUser(Object(OCA\\\\FullTextSearch_ElasticSearch\\\\Platform\\\\ElasticSearchPlatform), Object(OCA\\\\Files_FullTextSearch\\\\Provider\\\\FilesProvider), 'user234503')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/fulltextsearch\\\/lib\\\/Command\\\/Index.php(119): OCA\\\\FullTextSearch\\\\Command\\\\Index->indexProvider(Object(OCA\\\\Files_FullTextSearch\\\\Provider\\\\FilesProvider))\\n#19 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(264): OCA\\\\FullTextSearch\\\\Command\\\\Index->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#20 \\\/var\\\/www\\\/nextcloud\\\/core\\\/Command\\\/Base.php(161): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(874): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#22 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(228): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\FullTextSearch\\\\Command\\\\Index), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#23 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(130): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#24 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(173): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#25 \\\/var\\\/www\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#26 \\\/var\\\/www\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/nextcl...')\\n#27 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":160}","userAgent":"--","version":"13.0.1.1"}
{"reqId":"ymDiNxFvBrNANiLmHQCe","level":3,"time":"2018-04-17T20:32:17+02:00","remoteAddr":"","user":"--","app":"files_external","method":"--","url":"--","message":"Unauthorized","userAgent":"--","version":"13.0.1.1"}
{"reqId":"ymDiNxFvBrNANiLmHQCe","level":3,"time":"2018-04-17T20:32:17+02:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageInvalidException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Unauthorized\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(279): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientHttpException), '.noindex')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(320): OC\\\\Files\\\\Storage\\\\DAV->propfind('.noindex')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Storage.php(240): OC\\\\Files\\\\Storage\\\\DAV->file_exists('.noindex')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OCA\\\\Files_Sharing\\\\External\\\\Storage->file_exists('.noindex')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(244): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('.noindex')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(224): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('.noindex')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1322): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('.noindex')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1371): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), '.noindex', '\\\/user234503\\\/file...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(198): OC\\\\Files\\\\View->getFileInfo('\\\/user234503\\\/file...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(133): OC\\\\Files\\\\Node\\\\Root->get('\\\/user234503\\\/file...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(142): OC\\\\Files\\\\Node\\\\Folder->get('.noindex')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Service\\\/FilesService.php(154): OC\\\\Files\\\\Node\\\\Folder->nodeExists('.noindex')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Service\\\/FilesService.php(175): OCA\\\\Files_FullTextSearch\\\\Service\\\\FilesService->getFilesFromDirectory(Object(OCA\\\\FullTextSearch\\\\Model\\\\Runner), 'user234503', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Service\\\/FilesService.php(133): OCA\\\\Files_FullTextSearch\\\\Service\\\\FilesService->getFilesFromDirectory(Object(OCA\\\\FullTextSearch\\\\Model\\\\Runner), 'user234503', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_fulltextsearch\\\/lib\\\/Provider\\\/FilesProvider.php(186): OCA\\\\Files_FullTextSearch\\\\Service\\\\FilesService->getFilesFromUser(Object(OCA\\\\FullTextSearch\\\\Model\\\\Runner), 'user234503')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/fulltextsearch\\\/lib\\\/Service\\\/IndexService.php(122): OCA\\\\Files_FullTextSearch\\\\Provider\\\\FilesProvider->generateIndexableDocuments('user234503')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/fulltextsearch\\\/lib\\\/Command\\\/Index.php(146): OCA\\\\FullTextSearch\\\\Service\\\\IndexService->indexProviderContentFromUser(Object(OCA\\\\FullTextSearch_ElasticSearch\\\\Platform\\\\ElasticSearchPlatform), Object(OCA\\\\Files_FullTextSearch\\\\Provider\\\\FilesProvider), 'user234503')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/fulltextsearch\\\/lib\\\/Command\\\/Index.php(119): OCA\\\\FullTextSearch\\\\Command\\\\Index->indexProvider(Object(OCA\\\\Files_FullTextSearch\\\\Provider\\\\FilesProvider))\\n#18 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(264): OCA\\\\FullTextSearch\\\\Command\\\\Index->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#19 \\\/var\\\/www\\\/nextcloud\\\/core\\\/Command\\\/Base.php(161): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#20 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(874): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(228): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\FullTextSearch\\\\Command\\\\Index), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#22 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(130): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#23 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(173): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#24 \\\/var\\\/www\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#25 \\\/var\\\/www\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/nextcl...')\\n#26 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":841}","userAgent":"--","version":"13.0.1.1"}
{"reqId":"ymDiNxFvBrNANiLmHQCe","level":3,"time":"2018-04-17T20:32:17+02:00","remoteAddr":"","user":"--","app":"files_external","method":"--","url":"--","message":"Sabre\\HTTP\\ClientHttpException: Unauthorized","userAgent":"--","version":"13.0.1.1"}

```

It looks like Fulltextsearch stumbled over `.noindex`(?)
Indexing of external storage is disabled in fulltextsearch settings.

**Comment by daita** [comment]
please confirm if this bugs still occurs with the Release Candidate currently available

**Comment by DanScharon** [comment]
yes, this bug still occurs with RC2

**Comment by DanScharon** [comment]
the bug occured because of an orphaned external share in `oc_share_external`. The external share doesn't exist anymore (to be more specific: the user on that external server doesn't exist anymore). Unfortunately, Nextcloud doesn't really clear those orphaned entries (and users can't delete those themselves, just get an error). After deleting the external share in the database table the indexing for that user works.

**Comment by acsfer** [comment]
Can you please confirm this still hapens with both latest versions of Nexcloud and `files_fulltextsearch` apps?

**Comment by joshtrichards** [comment]
It's been 2+ years. Closing out this stale issue with no further reproducibility reported. Feel free to follow-up or open a new issue if it's still a valid bug.
